name: Yarn

on: push

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Yarn Lint
        run: yarn lint
      
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Yarn Build
        run: yarn build 
